# Generated by Django 2.0.13 on 2019-05-19 16:42

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('bookindx', models.IntegerField(default=1)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='likebook',
            name='user',
        ),
        migrations.RenameField(
            model_name='bookdata',
            old_name='info',
            new_name='decription',
        ),
        migrations.RemoveField(
            model_name='bookdata',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookdata',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='likeA',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='likeG',
        ),
        migrations.AddField(
            model_name='bookdata',
            name='array',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookdata',
            name='ndim',
            field=models.IntegerField(default=300),
        ),
        migrations.DeleteModel(
            name='LikeBook',
        ),
        migrations.AddField(
            model_name='bookrated',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likebooks', to='mybook.UserProfile'),
        ),
    ]
