# Generated by Django 2.0.13 on 2019-05-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0002_auto_20190520_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='arraylikebooksindxs',
            new_name='arrayratedbooksindxs',
        ),
        migrations.AlterField(
            model_name='bookrated',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratebooks', to='mybook.UserProfile'),
        ),
    ]
