# Generated by Django 2.0.13 on 2019-05-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0004_auto_20190529_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('bookindx', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklist', to='mybook.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='bookrated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratedbooks', to='mybook.UserProfile'),
        ),
    ]
