# Generated by Django 2.0.13 on 2019-05-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0005_auto_20190530_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listbook',
            name='bookindx',
        ),
    ]
