# Generated by Django 2.0.13 on 2019-06-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0006_remove_listbook_bookindx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrated',
            name='user',
        ),
        migrations.RenameField(
            model_name='bookdata',
            old_name='decription',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='bookdata',
            name='array',
        ),
        migrations.RemoveField(
            model_name='bookdata',
            name='ndim',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='array',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='arrayratedbooksindxs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastrecs',
        ),
        migrations.AddField(
            model_name='bookdata',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookdata',
            name='genre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookdata',
            name='keyword',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookRated',
        ),
    ]
